### PR TITLE
HSC-234: Add extension for Post-natale visit

### PR DESCRIPTION
**Pull request by kazlaw**
Link to ticket [here](https://mekomsolutions.atlassian.net/browse/HSC-234)

### CODE REVIEW

**Review by Ruhanga — CHANGES_REQUESTED** [review]
Thanks for the PR @kazlaw. However could you separate relevant changes from formatting changes. Difficult to review and know what actually changed when both are combined. Let's add the relevant changes and bring in formatting changes in a separate PR.

**Comment by kazlaw** [comment]
> Thanks for the PR @kazlaw. However could you separate relevant changes from formatting changes. Difficult to review and know what actually changed when both are combined. Let's add the relevant changes and bring in formatting changes in a separate PR.

This has been worked on, please have another look @Ruhanga

**Comment by Ruhanga** [comment]
Thanks @kazlaw. Any screenshot for reference?

**Comment by kazlaw** [comment]
@Ruhanga please see screenshot

image

**Review by Ruhanga — APPROVED** [review]

**Pull request merged**
